fastlane_version "1.91.0"

default_platform :ios

platform :ios do

  before_all do
    cocoapods
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cert
    sigh(force: true)
    gym(scheme: "A E S T H E T I C A M") # Build your app - more options available
    pilot
  end

  # desc "Deploy a new version to the App Store"
  # lane :appstore do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym(scheme: "A E S T H E T I C A M") # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

end
